### ISSUE TITLE
gym.error.NameNotFound: Environment RampControl doesn't exist.

### ISSUE THREAD

**Issue by byq-luo** [YuHan-Research-Group-SEU/Deep-Reinforcement-Learning-Network-for-Highway-Ramp-Metering#1]
(yolov7) PS D:\Deep-Reinforcement-Learning-Network-for-Highway-Ramp-Metering\Model and Training> python .\run.py
Traceback (most recent call last):
  File ".\run.py", line 31, in <module>
    env = gym.make('RampControl-v0').unwrapped
  File "D:\ProgramData\anaconda3\envs\yolov7\lib\site-packages\gym\envs\registration.py", line 569, in make
    _check_version_exists(ns, name, version)
  File "D:\ProgramData\anaconda3\envs\yolov7\lib\site-packages\gym\envs\registration.py", line 219, in _check_version_exists
    _check_name_exists(ns, name)
  File "D:\ProgramData\anaconda3\envs\yolov7\lib\site-packages\gym\envs\registration.py", line 198, in _check_name_exists
    f"Environment {name} doesn't exist{namespace_msg}. {suggestion_msg}"
gym.error.NameNotFound: Environment RampControl doesn't exist.

**Comment by YSXXXXXXX** [comment]
Hi, 
you need to **register** the environment through the `register` method before calling the `make` method.
The following documentation may be helpful for you to do that.
https://www.gymlibrary.dev/content/environment_creation/#registering-envs
